language: python
python:
    - '3.7'
before_install:
    - python -V
    - pip install poetry
    - poetry --version
install:
    - make build
script:
    - poetry run black -l 79 . --check
    - poetry run make pep8_checks
    - poetry run make test
