language: python
python:
    - '3.7'
before_install:
    - python -V
    - pip install poetry
    - poetry --version
install:
    - poetry install
script:
    - poetry run make format_checks
    - poetry run make test
